### ISSUE TITLE
Optimization 

### ISSUE THREAD

**Issue by papi2006** [PetitPrinc3/Deezer#1]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

*When you play a song and you click on the playlist option the app gets slow and when you close the list everything goes back to normal 

### **Additional context**

* The application is very good and I know it is still being improved but I only suggest that fix that would be very good, otherwise it seems excellent to me.

**Comment by PetitPrinc3** [comment]
Hi,

Thank you for your interest in the project.
Could you be more specific about the issue ?
I'm unsure about what you mean by "playlist options".

Best

**Comment by papi2006** [comment]
Hi, yes of course, here is an image.

When you open that option indicated in that image, the application becomes slow.

Apart from the icons that we see below in the image (the one with the letters and the list) they look almost hidden, I don't know if it's my cell phone or the application, it would be great to put it a little higher or fix it. 

![Screenshot_20241125-121029](https://github.com/user-attachments/assets/d98fa597-6e50-43b6-adce-e32db83cb01b)

**Comment by PetitPrinc3** [comment]
Thank you for the provided information.

> When you open that option indicated in that image, the application becomes slow.

Does the all app become slow or just the animation ? If so, try to change the refresh rate under settings > appearance > display mode.


> Apart from the icons that we see below in the image (the one with the letters and the list) they look almost hidden, I don't know if it's my cell phone or the application, it would be great to put it a little higher or fix it. 

Thank you for this information. I think I found the issue and will correct it (hopefully) in this week's build.

**Comment by papi2006** [comment]
> Thank you for the provided information.
> 
> > When you open that option indicated in that image, the application becomes slow.
> 
> Does the all app become slow or just the animation ? If so, try to change the refresh rate under settings > appearance > display mode.
> 

> > Apart from the icons that we see below in the image (the one with the letters and the list) they look almost hidden, I don't know if it's my cell phone or the application, it would be great to put it a little higher or fix it.
> 
> Thank you for this information. I think I found the issue and will correct it (hopefully) in this week's build.

The animation becomes slow but then the application becomes slow for a moment and then returns to normal and that happens every time I do that action, I already tried the display mode but it's still the same, thank you very much anyway .

**Comment by PetitPrinc3** [comment]
Hey,

Hopefully tonight's release should fix the overflow in the palyer screen. Can you please let me know ?

I am not able to diagnose the lagging in the queue screen yet. I have however taken it into account and will hopefully find a way to fix it.

Thank you for your feedback.

**Comment by papi2006** [comment]
> Hey,
> 
> Hopefully tonight's release should fix the overflow in the palyer screen. Can you please let me know ?
> 
> I am not able to diagnose the lagging in the queue screen yet. I have however taken it into account and will hopefully find a way to fix it.
> 
> Thank you for your feedback.

Hello 
Thank you very much for taking a little of your time to assist me.

**Comment by PetitPrinc3** [comment]
Latest commit  (https://github.com/PetitPrinc3/Deezer/commit/46ec336d32712584e080191b967aaca6cba757fd) should make the queue screen better and more optimized.
As I lack a better option / complete fix, I will consider this issue closed as I think the app is more than usable after the latest commit.

Thank you again for your feedback and interest.
