### ISSUE TITLE
download settings

### ISSUE THREAD

**Issue by senolfndk** [PetitPrinc3/Deezer#2]
downloaded song not showing in storage

**Comment by PetitPrinc3** [comment]
> 
> downloaded song not showing in storage

It is the intended behavior.
Just like the regular Deezer app, downloaded songs are only accessible within the app.

However, there is an option to export the downloaded tracks to local storage.
To do so, go to Settings > Export Tracks and click Export Tracks.

Cheers !

**Comment by senolfndk** [comment]
hmm tamam
