### ISSUE TITLE
[Enhancement] Downloading music

### ISSUE THREAD

**Issue by RAiNYRENJi** [PetitPrinc3/Deezer#3]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

* Currently, when a user wants to download a newly liked/favorited/saved song, the app re-downloads *all* previously downloaded songs in the list, starting from the first one. This is inefficient and wastes bandwidth.

---

## **Describe the solution you'd like**

* Implement automatic, immediate download of newly liked/favorited/saved songs. Instead of re-downloading the entire list, the app should only download the newly added track.
---

## **Describe alternatives you've considered**

* Display a download progress bar directly below the track being downloaded, similar to other music apps (e.g., Freezer, ReFreezer, Deezer). This provides better visual feedback than relying solely on notifications.

---

### **Additional context**

* N/A

**Comment by PetitPrinc3** [comment]
Fixed in today's release (v0.7.17)

Thank you for your feedback.
